---
title: "Figure2 Results"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#1. loading package and data

##1.1. package
```{r,message=FALSE,warning=FALSE}
library(xlsx)
library(magrittr)
library(dplyr)
library(plyr)
library(data.table)
library(survival)
library(survminer)
library(gghalves)
library(ComplexHeatmap)
library(factoextra)
```
##1.2. data
```{r,message=FALSE,warning=FALSE}
Express_ori <- xlsx::read.xlsx("../01_Data/TMA.xlsx",sheetIndex = 1)%>%as.data.frame()
rownames(Express_ori) <- paste0(Express_ori$Image,"_",Express_ori$location)

#Survival info
Info <- Express_ori[,c("DEATH","stage")]
Info%<>%mutate(
  stage = case_when(
  stage == "1" ~ "Stage I-II",
  stage == "2" ~ "Stage III-IV"
  )
)
Info$stage <- factor(Info$stage,levels = c("Stage I-II","Stage III-IV"))
Info%<>%mutate(
  DEATH = case_when(
  DEATH == "1" ~ "Yes",
  DEATH == "0" ~ "No"
  )
)
Info$DEATH <- factor(Info$DEATH,levels = c("Yes","No"))
```

#2. CD8 Type

##2.1. Classify
```{r}
CD8_Count <- Express_ori[,grep("CD8",colnames(Express_ori),ignore.case = T)]
CD8_Count <- rowSums(CD8_Count)
CD8_Count <- data.frame(
  row.names = names(CD8_Count),
  CD8 = CD8_Count%>%as.numeric()
)
#
stopifnot(rownames(CD8_Count)==rownames(Express_ori))
CD8_Count_percent <- sweep(CD8_Count, 1, Express_ori$Detections, FUN = "/")
#
CD8_Count_percent%<>%mutate(
  CD8_Type = case_when(
    CD8 >= quantile(CD8_Count_percent$CD8)[4] ~ "CD8High",
    CD8 <= quantile(CD8_Count_percent$CD8)[2] ~ "CD8Low",
    TRUE ~ "CD8Mid"
  )
)

CD8_Count_percent$CD8_Type <- factor(CD8_Count_percent$CD8_Type,levels = c("CD8Low","CD8Mid","CD8High"))
```
##2.2. Plot
```{r,fig.width = 5,fig.height = 4,message=FALSE,warning=FALSE}
#
ggplot(data = CD8_Count_percent,
       aes(x=CD8_Type, y=CD8*100, fill=CD8_Type)) +
    geom_half_violin(side = "r", color=NA, alpha=0.35) +
    geom_half_boxplot(side = "r", errorbar.draw = FALSE, width=0.2, linewidth=0.5) +
    geom_half_point_panel(side = "l", shape=21, size=2, color="white") +
    scale_fill_manual(values = c("CD8High" = "#FF7F00","CD8Mid" = "#A65628" ,"CD8Low" = "#F781BF"))+
    scale_y_log10()+
    labs(y="CD8 Cell Percentage (%)",x=NULL) +
    theme_bw() + 
    theme(axis.title = element_text(size = 16, color = "black"),
          axis.text = element_text(size=13, color = "black"),
          panel.grid =  element_blank(),legend.position = "none"
          )
```
##2.3. add CD8 information
```{r}
Info <- cbind(Info,CD8_Count_percent[,"CD8_Type",drop=FALSE])
```

#3. Cluster

##3.1. making data
```{r}
Express <- Express_ori[,c(17:34,36:38)]
colnames(Express) <- gsub("TIM.3","TIM-3",colnames(Express) )
colnames(Express) <- gsub("TIM3","TIM-3",colnames(Express) )
colnames(Express) <- gsub("PD.1","PD-1",colnames(Express) )
colnames(Express) <- gsub("\\."," ",colnames(Express) )
Express <- sweep(Express, 1, Express_ori$Detections, FUN = "/")
Express_ori$Samplename <- paste0(Express_ori$Image,"_",Express_ori$location)

#
Sur_info <- Express_ori[,c("Samplename","DEATH","OS")]
Sur_info %<>% as.data.table()
```
##3.2. Clustering
```{r}
#
col_dist  <-  factoextra::get_dist(Express,method = "maximum")
#
set.seed(123)
hclust <- hclust(col_dist,method = "ward.D2")
memb <- cutree(hclust,k = 3)
data <- data.table(Samplename= names(memb), Cluster=memb%>%as.character())
data$Cluster_labe <- mapvalues(data$Cluster,from = c("1","2","3"),to = c("Cluster3","Cluster2","Cluster1"))
data$Cluster <- data$Cluster_labe
data <- data[,c("Samplename","Cluster")]
data$Cluster%<>%as.factor()
setkey(data,Samplename)
#
Sur_info <- merge(Sur_info,data,by="Samplename")
Sur_info%<>%as.data.table()
#
Info$Cluster <- data[rownames(Info)]$Cluster
#
rm(col_dist,hclust,memb,data)
```
##3.3. Survival analysis

###3.3.1.  All cluster
```{r,fig.width=5,fig.height=5}
#
fit <- survfit(Surv(OS, DEATH) ~ Cluster, data = Sur_info)
ggsurvplot(fit, pval = T,
                risk.table = TRUE, 
                risk.table.col = "strata", 
                ggtheme = theme_bw() ,
                surv.median.line='hv',
                palette = c("Cluster=Cluster1"="#D92F20","Cluster=Cluster2"="#1B4586","Cluster=Cluster3"="#42B63F")
           )
```
###3.3.2. Cluster1 and Cluster2
```{r,fig.width=5,fig.height=5}
Data_surv_test <- Sur_info[Cluster%in%c("Cluster1","Cluster2")]
fit <- survfit(Surv(OS, DEATH) ~ Cluster, data = Data_surv_test)
#
ggsurvplot(fit, pval = T,
                risk.table = TRUE, 
                risk.table.col = "strata", 
                ggtheme = theme_bw() ,
                surv.median.line='hv',
                palette = c("Cluster=Cluster1"="#D92F20","Cluster=Cluster2"="#1B4586","Cluster=Cluster3"="#42B63F")
           )
```
###3.3.3. Cluster1 and Cluster3
```{r,fig.width=5,fig.height=5}
Data_surv_test <- Sur_info[Cluster%in%c("Cluster1","Cluster3")]
fit <- survfit(Surv(OS, DEATH) ~ Cluster, data = Data_surv_test)
#
ggsurvplot(fit, pval = T,
                risk.table = TRUE, 
                risk.table.col = "strata", 
                ggtheme = theme_bw() ,
                surv.median.line='hv',
                palette = c("Cluster=Cluster1"="#D92F20","Cluster=Cluster2"="#1B4586","Cluster=Cluster3"="#42B63F")
           )
```
###3.3.4. Cluster2 and Cluster3
```{r,fig.width=5,fig.height=5}
Data_surv_test <- Sur_info[Cluster%in%c("Cluster2","Cluster3")]
fit <- survfit(Surv(OS, DEATH) ~ Cluster, data = Data_surv_test)
#
ggsurvplot(fit, pval = T,
                risk.table = TRUE, 
                risk.table.col = "strata", 
                ggtheme = theme_bw() ,
                surv.median.line='hv',
                palette = c("Cluster=Cluster1"="#D92F20","Cluster=Cluster2"="#1B4586","Cluster=Cluster3"="#42B63F")
           )
```

#4. 绘制聚类后的热图结果

##4.1. 构建绘图表格
```{r,fig.height=4,fig.width=12}
#表达矩阵
Express_scale <- Express%>%scale()

#样本信息
stopifnot(rownames(Info)==rownames(Express_scale))
Top_anno <- Info[,c("DEATH","stage","CD8_Type")]

#更改行名
Name_conver <- data.table(
         stringsAsFactors = FALSE,
              check.names = FALSE,
          OldName = c("CD8 intratumoal","PD-1 CD8 intratumoal",
                      "PD-1 TIM-3 CD8 intratumoal","TIM-3 CD8 intratumoal",
                      "PD-1 intratumoal","PD-1 TIM-3 intratumoal",
                      "TIM-3 intratumoal",
                      "CD8 proximity","PD-1 CD8 proximity",
                      "PD-1 TIM-3 CD8 proximity","TIM-3 CD8 proximity",
                      "PD-1 proximity","PD-1 TIM-3 proximity",
                      "TIM-3 proximity",
                      "CD8 Distal","PD-1 CD8 Distal",
                      "PD-1 TIM-3 CD8 Distal","TIM-3 CD8 Distal",
                      "PD-1 Distal","PD-1 TIM-3 Distal",
                      "TIM-3 Distal"),
          NewName = c("PanCK+CD8+PD-1-TIM-3-_intra","PanCK+CD8+PD-1+TIM-3-_intra",
                      "PanCK+CD8+PD-1+TIM-3+_intra","PanCK+CD8+PD-1-TIM-3+_intra",
                      "PanCK+CD8-PD-1+TIM-3-_intra","PanCK+CD8-PD-1+TIM-3+_intra",
                      "PanCK+CD8-PD-1-TIM-3+_intra",
                      "PanCK-CD8+PD-1-TIM-3-_pro","PanCK-CD8+PD-1+TIM-3-_pro",
                      "PanCK-CD8+PD-1+TIM-3+_pro","PanCK-CD8+PD-1-TIM-3+_pro",
                      "PanCK-CD8-PD-1+TIM-3-_pro","PanCK-CD8-PD-1+TIM-3+_pro",
                      "PanCK-CD8-PD-1-TIM-3+_pro",
                      "PanCK-CD8+PD-1-TIM-3-_Dis","PanCK-CD8+PD-1+TIM-3-_Dis",
                      "PanCK-CD8+PD-1+TIM-3+_Dis","PanCK-CD8+PD-1-TIM-3+_Dis",
                      "PanCK-CD8-PD-1+TIM-3-_Dis","PanCK-CD8-PD-1+TIM-3+_Dis",
                      "PanCK-CD8-PD-1-TIM-3+_Dis")
)
stopifnot(Name_conver$OldName%in%colnames(Express_scale))
setkey(Name_conver,OldName)
colnames(Express_scale) <- Name_conver[colnames(Express_scale)]$NewName


#行分类信息
Right_Anno <- data.frame(
  Feature = colnames(Express_scale),
  Group=colnames(Express_scale),
  row.names = colnames(Express_scale)
)
Right_Anno$Group <- gsub("^.*_","",Right_Anno$Group)
Right_Anno$Group <- mapvalues(Right_Anno$Group,from = c("intra","pro","Dis"),to =c("intratumoal","proximity","Distal"))
Right_Anno$Group <- factor(Right_Anno$Group,levels = c("intratumoal","proximity","Distal"))
stopifnot(rownames(Right_Anno)==colnames(Express_scale))
```
##4.2. 绘制热图
```{r,fig.height=4,fig.width=12}
Heatmap(t(Express_scale),show_column_names = F,cluster_rows = T,cluster_columns = T,
        column_split = Info$Cluster,
        row_names_gp = gpar(fontsize=10),
        row_split = Right_Anno$Group,
        name = "Expression",show_parent_dend_line = F,
        col = circlize::colorRamp2(c(-2, 0, 2), c("#4575B4", "white", "#D73027")),border = T,border_gp = gpar(col='black',lwd=1.3),
        top_annotation = ComplexHeatmap::HeatmapAnnotation(
                                df = Top_anno,
                                col = list(
                                 DEATH=c("Yes"="black","No"="#FB6A4A"),
                                 stage=c("Stage I-II"="#E7E1EF","Stage III-IV"="#7A0177"),
                                 CD8_Type=c("CD8High" = "#FF7F00","CD8Mid" = "#A65628" ,"CD8Low" = "#F781BF" )
                                 )
                                ,show_annotation_name = T,simple_anno_size = unit(.35, "cm")
        ),
        column_gap = unit(1.4, "mm"),row_gap = unit(1.4, "mm"),cluster_column_slices = F
        )
```


